name: schoolapp_ui
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg : ^0.17.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  assets:
     - assets/images/OBO1.png
     - assets/images/OBO2.png
     - assets/images/OBO3.png
     - assets/images/OBO1img.png
     - assets/images/OBO2img.png
     - assets/images/OBO3img.png
     - assets/images/nxt1.png
     - assets/images/nxt2.png
     - assets/images/nxt3.png
     - assets/images/path.png
     - assets/images/icon.png
     - assets/images/SignIn.png
     - assets/images/rounder.png
     - assets/images/ForgotPassword.png
     - assets/images/fppath.png
     - assets/images/NoticeBoard/1.png
     - assets/images/NoticeBoard/2.png
     - assets/images/NoticeBoard/3.png
     - assets/images/NoticeBoard/4.png
     - assets/images/NoticeBoard/5.png
     - assets/images/NoticeBoard/6.png
     - assets/images/NoticeBoard/7.png
     - assets/images/HomeWork/1.png
     - assets/images/HomeWork/2.png
     - assets/images/HomeWork/3.png
     - assets/images/HomeWork/4.png
     - assets/images/HomeWork/5.png
     - assets/images/HomeWork/6.png
     - assets/images/HomeWork/7.png
     - assets/images/HomeWork/8.png
     - assets/images/HomeWork/9.png
     - assets/images/HomeWork/10.png
     - assets/images/HomeWork/11.png
     - assets/images/HomeWork/12.png
     - assets/images/dashBoard/MenuIcon.png
     - assets/images/dashBoard/ProPic.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
